name: Download oscomp testcases

inputs:
  image-release-url:
    description: 'URL of the image release'
    required: true
    type: string
  arch:
    description: 'Architecture of testcases'
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: Cache Testcases
    id: cache-testcases
    uses: actions/cache/restore@v4
    with:
      path: sdcard-${{ inputs.arch }}.img.gz
      key: sdcard-${{ inputs.arch }}.img.gz
  - name: Download testcases
    if: steps.cache-testcases.outputs.cache-hit != 'true'
    shell: bash
    run: |
      IMAGE_URL=${{ inputs.image-release-url }}/sdcard-${{ inputs.arch }}.img.gz
      wget ${IMAGE_URL}
  - uses: actions/cache/save@v4
    if: steps.cache-testcases.outputs.cache-hit != 'true'
    with:
      path: sdcard-${{ inputs.arch }}.img.gz
      key: sdcard-${{ inputs.arch }}.img.gz
